title = "OSGL"
gitRepoUrl = "https://github.com/Gunshot-Sound-Studios/osgl-graphics" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
projectName = "OSGL" 
baseUrl = "/osgl-graphics"
tagline = "Open-Source Graphical Library"

[footer]
style = "dark"
copyright = "Copyright © 2024 Gunshot Sound Studios."

[[navbar.items]]
href = "example.com"
label = "Intro"
position = "right"