title = "OSGL"
gitRepoUrl = "https://github.com/Gunshot-Sound-Studios/osgl-graphics" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
projectName = "OSGL" 

[footer]
style = "dark"
copyright = "Copyright © 2024 Gunshot Sound Studios."

