title = "OSGL"
gitRepoUrl = "https://github.com/Gunshot-Sound-Studios/osgl-graphics" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
tagline = "User-friendly and highly efficient rendering module."

[home]
enabled = true
includeReadme = false

# From git:
projectName = "OSGL"

[footer]
style = "dark"
copyright = "Copyright © 2024 Gunshot Sound Studios."
